<script setup>
import { computed, ref } from 'vue'
import { onLoad, onShareAppMessage } from '@dcloudio/uni-app'
import { getShareConfig } from '@/api'
import ShareButton from '@/components/ShareButton.vue'
const config = ref({ title: '分享好友 赚取佣金', subtitle: '好物推荐，轻松赚佣金', brand: '商城精选', imageUrl: '' })
const shareImage = computed(() => config.value.imageUrl || '')
const features = [['精选商品', '品质保障'], ['一键分享', '操作简单'], ['多重收益', '持续赚钱'], ['提现快速', '安全可靠']]
onLoad(async () => { try { const data = await getShareConfig(); if (data) config.value = { ...config.value, ...data } } catch (e) {} })
function join() { uni.navigateTo({ url: '/pages/my/dealer' }) }
function rules() { uni.navigateTo({ url: '/pages/my/rules' }) }
onShareAppMessage(() => ({ title: config.value.title, path: '/pages/my/share', ...(shareImage.value ? { imageUrl: shareImage.value } : {}) }))
</script>
<template>
  <view class="page">
    <view class="hero"><view class="hero-title">{{ config.title }}</view><view class="hero-sub">{{ config.subtitle }}</view><image v-if="shareImage" :src="shareImage" mode="aspectFill" /><view v-else class="hero-art"><view class="coin">¥</view><view class="gift" /></view></view>
    <view class="card benefits"><view class="section-title">分享好友 赚取佣金</view><view class="section-sub">邀请好友一起逛商城</view><view class="feature-grid"><view v-for="item in features" :key="item[0]" class="feature"><view class="feature-icon">✓</view><view class="feature-name">{{ item[0] }}</view><view class="feature-sub">{{ item[1] }}</view></view></view></view>
    <view class="card steps"><view class="card-title">如何成为分销员</view><view class="step"><view class="step-num">1</view><view><view class="step-title">点击下方“立即加入”</view><view class="step-sub">申请成为分销员</view></view></view><view class="step"><view class="step-num">2</view><view><view class="step-title">分享商品链接或图片</view><view class="step-sub">让好友通过你的分享购买</view></view></view><view class="step"><view class="step-num">3</view><view><view class="step-title">订单确认收货</view><view class="step-sub">获得相应的佣金</view></view></view></view>
    <button class="join" @click="join">立即加入分销</button><view class="rule-link" @click="rules">加入即表示同意《分销协议》 · 查看分销规则</view>
    <view class="quick-share"><ShareButton :title="config.title" path="/pages/my/share" /></view>
  </view>
</template>
<style scoped>
.page { min-height: 100vh; box-sizing: border-box; padding-bottom: 42rpx; background: #f5f8fa; color: #20262e; }.hero { position: relative; overflow: hidden; min-height: 280rpx; padding: 44rpx 34rpx; color: #fff; background: linear-gradient(135deg,#ff5b3f,#f54c2d); }.hero-title { font-size: 44rpx; font-weight: 800; }.hero-sub { margin-top: 14rpx; font-size: 23rpx; opacity: .9; }.hero image { position: absolute; right: 28rpx; bottom: 20rpx; width: 190rpx; height: 190rpx; border: 8rpx solid rgba(255,255,255,.8); border-radius: 18rpx; transform: rotate(5deg); }.hero-art { position: absolute; right: 45rpx; bottom: 22rpx; width: 210rpx; height: 190rpx; }.coin { position: absolute; top: 0; right: 22rpx; width: 66rpx; height: 66rpx; border-radius: 50%; color: #e78a17; background: #ffd56d; text-align: center; line-height: 66rpx; font-size: 32rpx; }.gift { position: absolute; right: 42rpx; bottom: 8rpx; width: 125rpx; height: 95rpx; border-radius: 16rpx; background: #ffbe4d; box-shadow: -45rpx -22rpx 0 -8rpx #ff8c33; transform: rotate(-8deg); }.card { margin: -30rpx 24rpx 20rpx; padding: 30rpx; border-radius: 22rpx; background: #fff; box-shadow: 0 8rpx 24rpx rgba(66,68,76,.06); }.benefits { position: relative; z-index: 1; }.section-title { color: #d94825; font-size: 34rpx; font-weight: 800; }.section-sub { margin-top: 8rpx; color: #9a9ea1; font-size: 22rpx; }.feature-grid { display: grid; grid-template-columns: repeat(4, 1fr); gap: 8rpx; margin-top: 28rpx; }.feature { text-align: center; }.feature-icon { margin: auto; width: 58rpx; height: 58rpx; border-radius: 50%; color: #ff633e; background: #fff0eb; line-height: 58rpx; font-size: 26rpx; font-weight: 800; }.feature-name { margin-top: 10rpx; font-size: 21rpx; font-weight: 650; }.feature-sub { margin-top: 5rpx; color: #9aa0a4; font-size: 18rpx; }.steps { margin-top: 20rpx; }.card-title { margin-bottom: 12rpx; font-size: 29rpx; font-weight: 750; }.step { display: flex; align-items: center; gap: 18rpx; padding: 18rpx 0; border-top: 1rpx solid #f0f1f1; }.step-num { width: 44rpx; height: 44rpx; border-radius: 50%; color: #fff; background: #ff6a4a; text-align: center; line-height: 44rpx; font-size: 22rpx; font-weight: 700; }.step-title { font-size: 23rpx; font-weight: 650; }.step-sub { margin-top: 5rpx; color: #9a9ea1; font-size: 19rpx; }.join { margin: 28rpx 30rpx 0; width: calc(100% - 60rpx); height: 78rpx; border: 0; border-radius: 39rpx; color: #fff; background: #ff4d36; font-size: 27rpx; line-height: 78rpx; }.join::after { border: 0; }.rule-link { margin-top: 16rpx; text-align: center; color: #8d969c; font-size: 19rpx; }.quick-share { display: flex; justify-content: center; margin-top: 18rpx; }.quick-share :deep(.share-button) { min-width: 200rpx; height: 68rpx; border-radius: 34rpx; background: #e8f3ff; color: #2677d8; font-size: 23rpx; }
</style>
